# TODO: set up flags, but would require splitting the `make test` command for each flag, or set the flag for each provider/model
# https://docs.codecov.com/docs/flags

# https://docs.codecov.com/docs/components
component_management:
  individual_components:
    - component_id: module_core  # this is an identifier that should not be changed
      name: core  # this is a display name, and can be changed freely
      paths:
        - gptme/*
    - component_id: module_tools
      name: tools
      paths:
        - gptme/tools/**
    - component_id: module_server
      name: server
      paths:
        - gptme/server/**
    - component_id: module_eval
      name: eval
      paths:
        - gptme/eval/**
