apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: gptmingdom
build:
  artifacts:
    - image: gptme-base
      context: .
      docker:
        dockerfile: scripts/Dockerfile
    - image: gptme-server
      context: .
      docker:
        dockerfile: scripts/Dockerfile.server
      requires:
        - image: gptme-base
          alias: BASE
manifests:
  rawYaml:
    - k8s/local/gptme/deployment.yaml
    - k8s/local/gptme/service.yaml
    - k8s/local/gptme/configmap.yaml
    - k8s/local/gptme/ingress.yaml
    - k8s/local/gptme/startup-script-configmap.yaml
  helm:
    releases:
      - name: ingress-nginx
        remoteChart: ingress-nginx
        repo: https://kubernetes.github.io/ingress-nginx
        namespace: gptmingdom
        #createNamespace: false
        #recreatePods: false
        #skipBuildDependencies: false
        useHelmSecrets: false
        #wait: false
        setValues:
          controller.replicaCount: 1
          defaultBackend.enabled: false
deploy:
  kubectl: {}
profiles:
  - name: dev
    activation:
      - kubeContext: minikube
    build:
      local:
        push: false
    portForward:
      - resourceType: service
        resourceName: gptme
        namespace: gptmingdom
        port: 8080
        localPort: 8080
