apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: gptmingdom
build:
  artifacts:
    - image: gptme-base
      context: .
      docker:
        dockerfile: scripts/Dockerfile
    - image: gptme-server
      context: .
      docker:
        dockerfile: scripts/Dockerfile.server
      requires:
        - image: gptme-base
          alias: BASE
    - image: fleet-operator
      context: ./agent-cluster/fleet-operator
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/local/gptme/deployment.yaml
    - k8s/local/gptme/service.yaml
    - k8s/local/gptme/configmap.yaml
    - k8s/local/gptme/ingress.yaml
    - k8s/local/gptme/startup-script-configmap.yaml
    # operator manifests for per-client pods
    - k8s/local/operator/deployment.yaml
    - k8s/local/operator/service.yaml
    - k8s/local/operator/rbac.yaml
    - k8s/local/operator/crd.yaml
    - k8s/local/operator/traefik-middleware.yaml
  helm:
    releases:
      - name: ingress-nginx
        remoteChart: ingress-nginx
        repo: https://kubernetes.github.io/ingress-nginx
        namespace: gptmingdom
        #createNamespace: false
        #recreatePods: false
        #skipBuildDependencies: false
        useHelmSecrets: false
        #wait: false
        setValues:
          controller.replicaCount: 1
          defaultBackend.enabled: false
      # Add Traefik CRDs first
      - name: traefik-crds
        remoteChart: traefik-crds
        repo: https://traefik.github.io/charts
        namespace: gptmingdom
        useHelmSecrets: false
      # Add Traefik API Gateway
      - name: traefik
        remoteChart: traefik
        repo: https://traefik.github.io/charts
        namespace: gptmingdom
        useHelmSecrets: false
        setValues:
          # Basic configuration
          deployment.replicas: 1
          # Enable dashboard and API
          dashboard.enabled: true
          dashboard.ingressRoute: true
          # Service configuration
          service.type: ClusterIP
          # Enable Kubernetes CRD support
          providers.kubernetesIngress.enabled: true
          providers.kubernetesCRD.enabled: true
          # Add proper resource requests/limits
          resources.requests.cpu: "100m"
          resources.requests.memory: "128Mi"
          resources.limits.cpu: "300m"
          resources.limits.memory: "256Mi"
          # Configure ports
          ports.web.port: 8000
          ports.websecure.port: 8443
          # Configure specific middlewares needed for per-client routing
          additionalArguments:
            - "--api.insecure=true"
            - "--api.dashboard=true"
            - "--log.level=INFO"
deploy:
  kubectl: {}
profiles:
  - name: dev
    activation:
      - kubeContext: minikube
    build:
      local:
        push: false
    portForward:
      - resourceType: service
        resourceName: gptme
        namespace: gptmingdom
        port: 8080
        localPort: 8080
      # Add port forwarding for Traefik dashboard
      - resourceType: service
        resourceName: traefik
        namespace: gptmingdom
        port: 9000 # Traefik dashboard port
        localPort: 9000
