apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: api-key-extractor
  namespace: gptmingdom
spec:
  # Extract API key from URL path and set as request header
  stripPrefix:
    prefixes:
      - /api/v1/
    forceSlash: false
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: client-identifier
  namespace: gptmingdom
spec:
  # Set client ID header from URL path segment
  headers:
    customRequestHeaders:
      X-API-Key: "{{ .RegexMatches.[0] }}"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: client-api-route
  namespace: gptmingdom
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/api/v1/{apiKey:[^/]+}/instance/{instanceID:[^/]+}`)
      kind: Rule
      middlewares:
        - name: client-identifier
        - name: api-key-extractor
      services:
        - name: fleet-operator
          port: 8080
