# Remove '#' to select a file or turn off linting.

# Linting with BLACK (Python) enhances code suggestions from LLMs. To disable linting, uncomment the relevant option in the linting settings.

# gpt-engineer can only read selected files. Including irrelevant files will degrade performance, cost additional tokens and potentially overflow token limit.

[linting]
# "linting" = "off"

[files]
# "CONTRIBUTING.md" = "selected"
# LICENSE = "selected"
# Makefile = "selected"
# "README.md" = "selected"
# "docs/Makefile" = "selected"
# "docs/_static/custom.css" = "selected"
# "docs/api.rst" = "selected"
# "docs/arewetiny.rst" = "selected"
# "docs/bot.md" = "selected"
# "docs/cli.rst" = "selected"
# "docs/conf.py" = "selected"
# "docs/demos.rst" = "selected"
# "docs/evals.rst" = "selected"
# "docs/examples.rst" = "selected"
# "docs/finetuning.md" = "selected"
# "docs/getting-started.rst" = "selected"
# "docs/index.rst" = "selected"
# "docs/make.bat" = "selected"
# "docs/prompts.rst" = "selected"
# "docs/providers.md" = "selected"
# "docs/server.rst" = "selected"
# "docs/tools.rst" = "selected"
# "gptme.toml" = "selected"
# "gptme/__init__.py" = "selected"
# "gptme/__main__.py" = "selected"
# "gptme/__version__.py" = "selected"
# "gptme/cli.py" = "selected"
# "gptme/codeblock.py" = "selected"
# "gptme/commands.py" = "selected"
# "gptme/config.py" = "selected"
# "gptme/constants.py" = "selected"
# "gptme/dirs.py" = "selected"
# "gptme/eval/__init__.py" = "selected"
# "gptme/eval/__main__.py" = "selected"
# "gptme/eval/agents.py" = "selected"
# "gptme/eval/execenv.py" = "selected"
# "gptme/eval/filestore.py" = "selected"
# "gptme/eval/main.py" = "selected"
# "gptme/eval/run.py" = "selected"
# "gptme/eval/suites/__init__.py" = "selected"
# "gptme/eval/suites/basic.py" = "selected"
# "gptme/eval/suites/browser.py" = "selected"
# "gptme/eval/suites/init_projects.py" = "selected"
# "gptme/eval/types.py" = "selected"
# "gptme/init.py" = "selected"
# "gptme/llm.py" = "selected"
# "gptme/llm_anthropic.py" = "selected"
# "gptme/llm_openai.py" = "selected"
# "gptme/llm_openai_models.py" = "selected"
# "gptme/logmanager.py" = "selected"
# "gptme/message.py" = "selected"
# "gptme/models.py" = "selected"
# "gptme/prompts.py" = "selected"
# "gptme/py.typed" = "selected"
# "gptme/reduce.py" = "selected"
# "gptme/server/__init__.py" = "selected"
# "gptme/server/__main__.py" = "selected"
# "gptme/server/api.py" = "selected"
# "gptme/server/cli.py" = "selected"
# "gptme/tabcomplete.py" = "selected"
# "gptme/tools/__init__.py" = "selected"
# "gptme/tools/_browser_playwright.py" = "selected"
# "gptme/tools/base.py" = "selected"
# "gptme/tools/browser.py" = "selected"
# "gptme/tools/chats.py" = "selected"
# "gptme/tools/gh.py" = "selected"
# "gptme/tools/patch.py" = "selected"
# "gptme/tools/python.py" = "selected"
# "gptme/tools/read.py" = "selected"
# "gptme/tools/save.py" = "selected"
# "gptme/tools/shell.py" = "selected"
# "gptme/tools/subagent.py" = "selected"
# "gptme/tools/tmux.py" = "selected"
# "gptme/tools/youtube.py" = "selected"
# "gptme/useredit.py" = "selected"
# "gptme/util.py" = "selected"
# "poetry.lock" = "selected"
# "pyproject.toml" = "selected"
# "scripts/Dockerfile" = "selected"
# "scripts/Dockerfile.eval" = "selected"
# "scripts/bump_version.sh" = "selected"
# "scripts/describe_api.py" = "selected"
# "scripts/format_log.sh" = "selected"
# "scripts/get-last-version.sh" = "selected"
# "scripts/git-shim.sh" = "selected"
# "scripts/gpt_todoer.py" = "selected"
# "scripts/list_user_messages.py" = "selected"
# "scripts/shorten_details.py" = "selected"
# "scripts/strip.sh" = "selected"
# "scripts/summarize_project.py" = "selected"
# "static/index.html" = "selected"
# "static/style.css" = "selected"
# "tests/test-integration.sh" = "selected"
# "tests/test_browser.py" = "selected"
# "tests/test_cli.py" = "selected"
# "tests/test_codeblock.py" = "selected"
# "tests/test_config.py" = "selected"
# "tests/test_eval.py" = "selected"
# "tests/test_logmanager.py" = "selected"
# "tests/test_message.py" = "selected"
# "tests/test_prompts.py" = "selected"
# "tests/test_reduce.py" = "selected"
# "tests/test_server.py" = "selected"
# "tests/test_shell.py" = "selected"
# "tests/test_tabcomplete.py" = "selected"
# "tests/test_tools_chats.py" = "selected"
# "tests/test_tools_patch.py" = "selected"
# "tests/test_tools_python.py" = "selected"
# "tests/test_tools_shell.py" = "selected"
# "tests/test_tools_subagent.py" = "selected"
# "tests/test_util.py" = "selected"
# "train/collect.py" = "selected"
